In [1]:
from sklearn.metrics.pairwise import rbf_kernel
import numpy as np
from scipy import sparse 
import sys
from gaussiandata import SyntheticTarget
from onlinePrototypes import protonline
from onlineCriticism import crionline
#import greedy_functions
import math
import scipy

(1000, 2) => 100


In [2]:
SEED = 666
number_of_gaussians = 2
ex = SyntheticTarget(seed=SEED, dist_components=number_of_gaussians)

N = 1000
M = 10
data = ex.draw_sample(N)
print  data.size
print data[(2,3,4),:]
gamma = 2
kernel_matrix = rbf_kernel(data, gamma = gamma)

2000
[[ 2.58801945 -4.10201855]
 [-1.1745815  -3.81182871]
 [ 3.41529632 -3.59914177]]


In [3]:
def rbf(x,y, gamma):
    x = np.asarray(x)
    y = np.asarray(y)
    return scipy.exp(-gamma*np.linalg.norm(x-y))

def our_rbf_kernel(current_kernel_subset,  gamma, x_new, n, M, data, current_indices):
    new_row = np.zeros(n+1)
    new_col = np.zeros(M)
    for i in range(n+1):
        new_row[i] = rbf(x = x_new, y = data[i], gamma = gamma)
         
    new_col = new_row[current_indices]
    new_row = np.matrix(new_row)
    new_col = np.matrix(new_col)

    new_kernel_subset = np.hstack((current_kernel_subset, new_col.T))
    new_kernel_subset = np.vstack((new_kernel_subset, new_row))
    
    return new_kernel_subset

In [4]:
gamma = 2
prototype_indices = np.arange(M) #assign first M points as prototypes. CONSIDER another method later.
criticism_indices = np.arange(M, 2*M) # assign second M points as prototypes.

#calculate the initial kernel matrix for the first M points
#current_kernel_matrix_proto = rbf_kernel(data[prototype_indices,:], gamma=gamma)


#current_kernel_matrix_criticism = rbf_kernel(data[criticism_indices,:], gamma = gamma) #to check with Petya

current_kernel_matrix = rbf_kernel(data[range(2*M)], gamma = gamma)
current_kernel_matrix_proto = current_kernel_matrix[:M]
current_kernel_matrix_criticism = current_kernel_matrix[range(M, 2*M)]


for i in range(2*M, N):
    
    new_point_index = i # assign the new data point index
    accept = 1 # decide whether to skip the criticism part or not 
    
    #prototype part
    if accept == 1:
        #add new column and row to the kernel matrix for the new point; 
        #kernel matrix is always growing
        #current_kernel_subset,  gamma, x_new, n, timeseries):

        new_kernel_matrix_proto = our_rbf_kernel(current_kernel_subset = current_kernel_matrix_proto, gamma = gamma,  
                                                 x_new= data[i], n = i, M = M,  data = data[range(i+1)], 
                                                 current_indices = prototype_indices)

        #run the greedy algorithm on these M+1 data points to select M prototypes
        print prototype_indices
        prototype_indices_temp = protonline(new_kernel_matrix_proto, 
                                                  selectedprotos = prototype_indices, m = M)
           
        if (prototype_indices_temp == prototype_indices).all():
            accept == 0
        
        else:
            prototype_indices = prototype_indices_temp # update the indices
            current_kernel_matrix_proto = new_kernel_matrix_proto # update the kernel matrix
    
    
    #criticism part
    if accept == 0:
        
        new_kernel_matrix_criticism = our_rbf_kernel(current_kernel_subset = current_kernel_matrix_criticism, 
                                                     gamma = gamma,  x_new= data[i], n = i, M = M, 
                                                     data = data[range(i+1)], current_indices = criticism_indices)
        
        #run the greedy algorithm on these M+1 data points to select M criticism
        criticism_indices_temp = crionline(new_kernel_matrix_criticism, 
                                                  selectedprotos = prototype_indices, selectedcritic = criticism_indices, c = M, reg='logdet')

        
        if (criticism_indices_temp == criticism_indices).all():
            accept == 0
        
        else:
            criticism_indices = criticism_indices_temp # update the indices
            current_kernel_matrix_criticism = new_kernel_matrix_criticism # update the kernel matrix
    
    

[0 1 2 3 4 5 6 7 8 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 0  1  2  3  4  5  6  7  8  9 20]
[[ 0.2337025 ]
 [ 0.20655686]
 [ 0.23959615]
 [ 0.61542   ]
 [ 0.2905379 ]
 [ 0.38624166]
 [ 0.44004073]
 [ 0.50677863]
 [ 0.68791655]
 [ 0.26476668]
 [ 0.22448578]]
(11, 21)
k_subset2
[[  1.00000000e+00   2.44384996e-24   1.09287834e-16   1.78538050e-01
    4.70874142e-24   5.21208285e-01   2.43378493e-01   2.12726543e-03
    5.76250991e-02   3.09682471e-23   1.41849232e-05]
 [  2.44384996e-24   1.00000000e+00   5.76932476e-02   7.76049625e-19
    6.97977605e-01   4.56124011e-22   2.42770944e-17   9.61835919e-12
    1.27530158e-17   1.14309993e-01   1.16831491e-01]
 [  1.09287834e-16   5.76932476e-02   1.00000000e+00   4.26675735e-13
    1.53424889e-01   1.74644962e-15   3.77699449e-11   1.53614797e-07
    2.00210962e-12   2.54595991e-01   7.39719771e-02]
 [  1.78538050e-01   7.76049625e-19   4.26675735e-13   1.00000000e+00
    4.59371239e-19   6.94873514e-01   4.66579454e-01   1.32771655e-01
 

IndexError: index 88 is out of bounds for axis 0 with size 11

In [ ]:
np.arange(M+1)

In [ ]:
current_kernel_subset =  np.random.randn(5,10)
our_rbf_kernel(current_kernel_subset = current_kernel_subset, gamma = 2, x_new = 6, n = 10, timeseries = np.arange(10))


In [ ]:
new_row = np.zeros(10)

In [ ]:
print new_row

In [1]:
range(10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
A =  np.random.randn(5,10)
B =  np.random.randn(5,10)


In [72]:
prototype_indices =range(M) 
prototype_indices

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [88]:
print s1array.shape

IndexError: index 88 is out of bounds for axis 0 with size 11

In [5]:
print s1array.shape

NameError: name 's1array' is not defined