In [13]:
from sklearn.metrics.pairwise import rbf_kernel
import numpy as np
from scipy import sparse 
import sys
from gaussiandata import SyntheticTarget
from greedyfunctions import greedy_select_protos
#import greedy_functions
import math
import scipy

In [12]:
SEED = 666
number_of_gaussians = 2
ex = SyntheticTarget(seed=SEED, dist_components=number_of_gaussians)

N = 10000
M = 100
data = ex.draw_sample(N)
print data[(2,3,4),:]
gamma = 2
kernel_matrix = rbf_kernel(data, gamma = gamma)

[[ 3.64703263 -3.77549178]
 [-0.42829885 -3.19168078]
 [ 3.175412   -3.63978629]]


In [34]:
prototype_indices = greedy_select_protos(kernel_matrix, candidate_indices = np.array(range(N)), m = M)

In [1]:
print(prototype_indices)

NameError: name 'prototype_indices' is not defined

In [13]:
gamma = 2
prototype_indices = np.arange(M) #assign first M points as prototypes. CONSIDER another method later.
criticism_indices = np.arange(M, 2*M) # assign second M points as prototypes.

#calculate the initial kernel matrix for the first M points
current_kernel_matrix_proto = rbf_kernel(data[prototype_indices,:], gamma=gamma)

#current_kernel_matrix_criticism = rbf_kernel(data[np.array(prototype_indices, criticism_indices),:], gamma = gamma)

for i in range(2*M, N):
    new_point_index = i # assign the new data point index
    
    accept == 1 # decide whether to skip the criticism part or not 
    
    #prototype part
    if accept == 1:
        #add new column and row to the kernel matrix for the new point; 
        #kernel matrix is always growing
        #current_kernel_subset,  gamma, x_new, n, timeseries):
        new_kernel_matrix_proto = kernel_fn(gamma = gamma, current_kernel_subset = current_kernel_matrix_proto, n = i, timeseries = timeseries, x_new= x_new)
        
        #run the greedy algorithm on these M+1 data points to select M prototypes
        prototype_indices_temp = greedy_select_protos(new_kernel_matrix_proto, 
                                                  candidate_indices = np.vstack((prototype_indices, i-1)), m = M)
    
        if prototype_indices_temp == prototype_indices:
            accept == 0
        
        else:
            prototype_indices = prototype_indices_temp # update the indices
            current_kernel_matrix_proto = new_kernel_matrix_proto # update the kernel matrix
    
    
    #criticism part
    if accept == 0:
        
    
    

SyntaxError: invalid syntax (<ipython-input-13-63edf8dd6ac8>, line 16)

In [16]:
np.arange(M+1)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [37]:
def rbf(x,y, gamma):
    x = np.asarray(x)
    y = np.asarray(y)
    return scipy.exp(-gamma*np.linalg.norm(x-y))

def our_rbf_kernel(current_kernel_subset,  gamma, x_new, n, timeseries):
    new_row = np.zeros(n)
    for i in range(n):
         new_row[i] = rbf(x = x_new, y = timeseries[i], gamma = gamma)
    new_kernel_subset = np.vstack((current_kernel_subset, new_row))
    return new_kernel_subset

In [38]:
current_kernel_subset =  np.random.randn(5,10)
our_rbf_kernel(current_kernel_subset = current_kernel_subset, gamma = 2, x_new = 6, n = 10, timeseries = np.arange(10))


array([[ -9.16671887e-01,   8.15744137e-01,   7.68242472e-01,
          5.29271715e-04,   3.26204577e-02,   1.17723196e+00,
          7.16696933e-01,  -1.25678253e+00,  -1.19789775e+00,
         -4.77838275e-02],
       [ -1.07359524e+00,   8.33294723e-01,  -1.49609838e+00,
         -1.26590500e+00,   1.44965188e+00,   2.47288280e+00,
         -8.05568947e-01,   1.37749325e+00,   1.60388415e+00,
          1.31527918e+00],
       [ -2.11285415e-01,   3.48900936e-01,   4.16801757e-01,
         -4.69922782e-01,  -2.20001929e+00,   7.83464954e-01,
         -4.50360278e-01,   7.10973767e-01,   1.03880549e+00,
          1.51370091e+00],
       [  2.39208553e-01,   9.63990087e-01,  -1.74088674e-01,
          1.85270323e-01,   5.86067323e-01,  -7.78856176e-01,
          1.30084613e+00,  -5.06992131e-01,   1.84909571e+00,
         -1.05745993e-01],
       [ -9.52897691e-01,   1.18977466e-01,  -5.82416949e-01,
          5.15202645e-01,   1.95096023e+00,   6.59321331e-01,
         -4.97409736e-01

In [28]:
new_row = np.zeros(10)

In [29]:
print new_row

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
A =  np.random.randn(5,10)
B =  np.random.randn(5,10)
